var json = {
    "match1": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "08:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Clearwater"],
        "gAway": ["Away Team: ", "OCU"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match2": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "09:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "LFC"],
        "gAway": ["Away Team: ", "New Tampa"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    }
}