var json = {
    "match1": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "08:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match2": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "09:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match3": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "11:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match4": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "12:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match5": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "14:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match6": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "15:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match7": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "17:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match8": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "18:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match9": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "20:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match10": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "08:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match11": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "09:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match12": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "11:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match13": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "12:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match14": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "14:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match15": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "15:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match16": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "17:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match17": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "18:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    },
    "match18": {
        "gDate": ["Game Date: ", "2012-10-28"],
        "gTime": ["Game Time: ", "20:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match19": {
        "gDate": ["Game Date: ", "2012-10-29"],
        "gTime": ["Game Time: ", "08:00"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "adam@test.com"],
        "ar1": ["AR 1: ", "Matthew C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "matt@test.com"],
        "ar2": ["AR 2: ", "Bill C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "bill@test.com"]
    },
    "match20": {
        "gDate": ["Game Date: ", "2012-10-29"],
        "gTime": ["Game Time: ", "09:30"],
        "gField": ["Game Field: ", "1A"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "Home"],
        "gAway": ["Away Team: ", "Away"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill C."],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "bill@test.com"],
        "ar1": ["AR 1: ", "Adam C."],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "adam@test.com"],
        "ar2": ["AR 2: ", "Matthew C."],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "matt@test.com"]
    }
};